export interface Ticker {
  favorited: boolean;
  symbol: string;
  name: string;
}

export const tickers: Ticker[] = [
  { favorited: false, symbol: "MSFT", name: "Microsoft Corporation" },
  { favorited: false, symbol: "AAPL", name: "Apple Inc" },
  { favorited: false, symbol: "NVDA", name: "NVIDIA Corporation" },
  { favorited: false, symbol: "GOOG", name: "Alphabet Inc." },
  { favorited: false, symbol: "AMZN", name: " Amazon.com, Inc." },
  { favorited: false, symbol: "META", name: " Meta Platforms, Inc." },
  { favorited: false, symbol: "BRK-B", name: " Berkshire Hathaway Inc." },
  { favorited: false, symbol: "LLY", name: " Eli Lilly and Company" },
  { favorited: false, symbol: "AVGO", name: "Broadcom Inc." },
  { favorited: false, symbol: "V", name: " Visa Inc." },
  { favorited: false, symbol: "JPM", name: " JPMorgan Chase & Co." },
  { favorited: false, symbol: "TSLA", name: " Tesla, Inc." },
  { favorited: false, symbol: "WMT", name: " Walmart Inc." },
  { favorited: false, symbol: "UNH", name: " UnitedHealth Group Incorporated" },
  { favorited: false, symbol: "XOM", name: "Exxon Mobil Corporation" },
  { favorited: false, symbol: "MA", name: "Mastercard Incorporated" },
  { favorited: false, symbol: "HD", name: "The Home Depot, Inc." },
  { favorited: false, symbol: "PG", name: " The Procter & Gamble Company" },
  { favorited: false, symbol: "JNJ", name: "Johnson & Johnson" },
  { favorited: false, symbol: "ORCL", name: "Oracle Corporation" },
  { favorited: false, symbol: "COST", name: "Costco Wholesale Corporation" },
  { favorited: false, symbol: "MRK", name: "Merck & Co., Inc." },
  { favorited: false, symbol: "ABBV", name: " AbbVie Inc." },
  { favorited: false, symbol: "CRM", name: " Salesforce, Inc." },
  { favorited: false, symbol: "BAC", name: " Bank of America Corporation" },
  { favorited: false, symbol: "CVX", name: "Chevron Corporation" },
  { favorited: false, symbol: "AMD", name: "Advanced Micro Devices, Inc." },
  { favorited: false, symbol: "NFLX", name: " Netflix, Inc." },
  { favorited: false, symbol: "KO", name: "The Coca-Cola Company" },
  { favorited: false, symbol: "PEP", name: "PepsiCo, Inc." },
  { favorited: false, symbol: "ADBE", name: " Adobe Inc." },
  { favorited: false, symbol: "LIN", name: " Linde plc" },
  { favorited: false, symbol: "DIS", name: "The Walt Disney Company" },
  { favorited: false, symbol: "TMO", name: "Thermo Fisher Scientific Inc." },
  { favorited: false, symbol: "ACN", name: " Accenture plc" },
  { favorited: false, symbol: "MCD", name: "McDonald's Corporation" },
  { favorited: false, symbol: "CSCO", name: "Cisco Systems, Inc." },
  { favorited: false, symbol: "WFC", name: "Wells Fargo & Company" },
  { favorited: false, symbol: "ABT", name: "Abbott Laboratories" },
  { favorited: false, symbol: "TMUS", name: "T-Mobile US, Inc." },
  { favorited: false, symbol: "GE", name: "General Electric Company" },
  { favorited: false, symbol: "QCOM", name: "QUALCOMM Incorporated" },
  { favorited: false, symbol: "INTC", name: "Intel Corporation" },
  { favorited: false, symbol: "DHR", name: "Danaher Corporation" },
  { favorited: false, symbol: "INTU", name: "Intuit Inc." },
  { favorited: false, symbol: "CAT", name: "Caterpillar Inc." },
  { favorited: false, symbol: "VZ", name: "Verizon Communications Inc." },
  { favorited: false, symbol: "IBM", name: "International Business Machines Corporation" },
  { favorited: false, symbol: "AMAT", name: "Applied Materials, Inc." },
  { favorited: false, symbol: "CMCS", name: "Comcast Corporation" },
  { favorited: false, symbol: "UBER", name: "Uber Technologies, Inc." },
  { favorited: false, symbol: "AXP", name: "American Express Company" },
  { favorited: false, symbol: "TXN", name: "Texas Instruments Incorporated" },
  { favorited: false, symbol: "PFE", name: "Pfizer Inc." },
  { favorited: false, symbol: "BX", name: "Blackstone Inc." },
  { favorited: false, symbol: "NOW", name: "ServiceNow, Inc." },
  { favorited: false, symbol: "MS", name: "Morgan Stanley" },
  { favorited: false, symbol: "AMGN", name: "Amgen Inc." },
  { favorited: false, symbol: "COP", name: "Conoco Phillips" },
  { favorited: false, symbol: "UNP", name: "Union Pacific Corporation" },
  { favorited: false, symbol: "LOW", name: "Lowe's Companies, Inc." },
  { favorited: false, symbol: "NKE", name: " NIKE, Inc." },
  { favorited: false, symbol: "ISRG", name: " Intuitive Surgical, Inc." },
  { favorited: false, symbol: "PM", name: " Philip Morris International Inc." },
  { favorited: false, symbol: "SYK", name: " Stryker Corporation" },
  { favorited: false, symbol: "SPGI", name: "S&P Global Inc." },
  { favorited: false, symbol: "GS", name: " The Goldman Sachs Group, Inc." },
  { favorited: false, symbol: "HON", name: " Honeywell International Inc." },
  { favorited: false, symbol: "MU", name: " Micron Technology, Inc." },
  { favorited: false, symbol: "SCHW", name: " The Charles Schwab Corporation" },
  { favorited: false, symbol: "RTX", name: "RTX Corp" },
  { favorited: false, symbol: "NEE", name: "NextEra Energy, Inc." },
  { favorited: false, symbol: "LRCX", name: " Lam Research Corporation" },
  { favorited: false, symbol: "BKNG", name: "Booking Holdings Inc." },
  { favorited: false, symbol: "ETN", name: " Eaton Corporation plc" },
  { favorited: false, symbol: "T", name: "AT&T Inc." },
  { favorited: false, symbol: "UPS", name: " United Parcel Service, Inc." },
  { favorited: false, symbol: "BLK", name: " BlackRock, Inc." },
  { favorited: false, symbol: "PGR", name: " The Progressive Corporation" },
  { favorited: false, symbol: "ELV", name: "Elevance Health Inc." },
  { favorited: false, symbol: "C", name: " Citigroup Inc." },
  { favorited: false, symbol: "PLD", name: " Prologis, Inc." },
  { favorited: false, symbol: "TJX", name: " The TJX Companies, Inc." },
  { favorited: false, symbol: "BA", name: " The Boeing Company" },
  { favorited: false, symbol: "MDT", name: "Medtronic plc" },
  { favorited: false, symbol: "DE", name: "Deere & Company" },
  { favorited: false, symbol: "LMT", name: "Lockheed Martin Corporation" },
  { favorited: false, symbol: "VRTX", name: "Vertex Pharmaceuticals Incorporated" },
  { favorited: false, symbol: "BMY", name: "Bristol-Myers Squibb Company" },
  { favorited: false, symbol: "ABNB", name: "Airbnb, Inc." },
  { favorited: false, symbol: "REGN", name: " Regeneron Pharmaceuticals, Inc." },
  { favorited: false, symbol: "CB", name: " Chubb Limited" },
  { favorited: false, symbol: "CI", name: "Cigna Corporation" },
  { favorited: false, symbol: "SBUX", name: "Starbucks Corporation" },
  { favorited: false, symbol: "ADP", name: "Automatic Data Processing, Inc." },
  { favorited: false, symbol: "MMC", name: " Marsh & McLennan Companies, Inc." },
  { favorited: false, symbol: "CVS", name: " CVS Health Corporation" },
  { favorited: false, symbol: "BSX", name: "Boston Scientific Corporation" },
  { favorited: false, symbol: "MDLZ", name: "Mondelez International, Inc." },
  { favorited: false, symbol: "ADI", name: " Analog Devices, Inc." },
  { favorited: false, symbol: "FI", name: " Fiserv, Inc." },
  { favorited: false, symbol: "KLAC", name: " KLA Corporation" },
  { favorited: false, symbol: "AMT", name: "American Tower Corporation" },
  { favorited: false, symbol: "PANW", name: "Palo Alto Networks, Inc." },
  { favorited: false, symbol: "GILD", name: " Gilead Sciences, Inc." },
  { favorited: false, symbol: "ANET", name: " Arista Networks, Inc." },
  { favorited: false, symbol: "HCA", name: " HCA Healthcare, Inc." },
  { favorited: false, symbol: "SNPS", name: " Synopsys, Inc." },
  { favorited: false, symbol: "SHW", name: "The Sherwin-Williams Company" },
  { favorited: false, symbol: "WM", name: "Waste Management, Inc." },
  { favorited: false, symbol: "CDNS", name: " Cadence Design Systems, Inc." },
  { favorited: false, symbol: "CMG", name: " Chipotle Mexican Grill, Inc." },
  { favorited: false, symbol: "TGT", name: " Target Corporation" },
  { favorited: false, symbol: "ITW", name: "Illinois Tool Works Inc." },
  { favorited: false, symbol: "SLB", name: " Schlumberger Limited" },
  { favorited: false, symbol: "ICE", name: "Intercontinental Exchange, Inc." },
  { favorited: false, symbol: "SO", name: " The Southern Company" },
  { favorited: false, symbol: "GD", name: "General Dynamics Corporation" },
  { favorited: false, symbol: "MO", name: "Altria Group, Inc." },
  { favorited: false, symbol: "CME", name: " CME Group Inc." },
  { favorited: false, symbol: "ZTS", name: " Zoetis Inc." },
  { favorited: false, symbol: "EQIX", name: " Equinix, Inc." },
  { favorited: false, symbol: "EOG", name: " EOG Resources, Inc." },
  { favorited: false, symbol: "CL", name: "Colgate-Palmolive Company" },
  { favorited: false, symbol: "MAR", name: "Marriott International, Inc." },
  { favorited: false, symbol: "DUK", name: " Duke Energy Corporation" },
  { favorited: false, symbol: "CSX", name: "CSX Corporation" },
  { favorited: false, symbol: "MCO", name: "Moody's Corporation" },
  { favorited: false, symbol: "PYPL", name: "PayPal Holdings, Inc." },
  { favorited: false, symbol: "MPC", name: "Marathon Petroleum Corporation" },
  { favorited: false, symbol: "PH", name: "Parker-Hannifin Corporation" },
  { favorited: false, symbol: "NOC", name: "Northrop Grumman Corporation" },
  { favorited: false, symbol: "MCK", name: "McKesson Corporation" },
  { favorited: false, symbol: "FDX", name: "FedEx Corporation" },
  { favorited: false, symbol: "BDX", name: "Becton, Dickinson and Company" },
  { favorited: false, symbol: "CTAS", name: "Cintas Corporation" },
  { favorited: false, symbol: "TDG", name: "TransDigm Group Incorporated" },
  { favorited: false, symbol: "PSX", name: "Phillips 66" },
  { favorited: false, symbol: "APH", name: "Amphenol Corporation" },
  { favorited: false, symbol: "TT", name: "Trane Technologies plc" },
  { favorited: false, symbol: "USB", name: "U.S. Bancorp" },
  { favorited: false, symbol: "ORLY", name: "O'Reilly Automotive, Inc." },
  { favorited: false, symbol: "AON", name: " Aon plc" },
  { favorited: false, symbol: "FCX", name: "Freeport-McMoRan Inc." },
  { favorited: false, symbol: "ECL", name: " Ecolab Inc." },
  { favorited: false, symbol: "PCAR", name: " PACCAR Inc" },
  { favorited: false, symbol: "EMR", name: "Emerson Electric Co." },
  { favorited: false, symbol: "MNST", name: " Monster Beverage Corporation" },
  { favorited: false, symbol: "PNC", name: "The PNC Financial Services Group, Inc." },
  { favorited: false, symbol: "NXPI", name: " NXP Semiconductors N.V." },
  { favorited: false, symbol: "SMCI", name: " Super Micro Computer, Inc." },
  { favorited: false, symbol: "PXD", name: " Pioneer Natural Resources Company" },
  { favorited: false, symbol: "ROP", name: "Roper Technologies, Inc." },
  { favorited: false, symbol: "RSG", name: " Republic Services, Inc." },
  { favorited: false, symbol: "CEG", name: " Constellation Energy Corporation" },
  { favorited: false, symbol: "MSI", name: "Motorola Solutions, Inc." },
  { favorited: false, symbol: "EW", name: " Edwards Lifesciences Corporation" },
  { favorited: false, symbol: "MMM", name: "3M Company" },
  { favorited: false, symbol: "SPG", name: "Simon Property Group, Inc." },
  { favorited: false, symbol: "OXY", name: " Occidental Petroleum Corporation" },
  { favorited: false, symbol: "ADSK", name: "Autodesk, Inc." },
  { favorited: false, symbol: "NSC", name: " Norfolk Southern Corporation" },
  { favorited: false, symbol: "VLO", name: "Valero Energy Corporation" },
  { favorited: false, symbol: "AZO", name: "AutoZone, Inc." },
  { favorited: false, symbol: "CPRT", name: " Copart, Inc." },
  { favorited: false, symbol: "COF", name: " Capital One Financial Corporation" },
  { favorited: false, symbol: "AJG", name: "Arthur J. Gallagher & Co." },
  { favorited: false, symbol: "APD", name: " Air Products and Chemicals, Inc." },
  { favorited: false, symbol: "DXCM", name: " DexCom, Inc." },
  { favorited: false, symbol: "HLT", name: " Hilton Worldwide Holdings Inc." },
  { favorited: false, symbol: "DHI", name: " D.R. Horton, Inc." },
  { favorited: false, symbol: "MET", name: " MetLife, Inc." },
  { favorited: false, symbol: "AIG", name: " American International Group, Inc." },
  { favorited: false, symbol: "EL", name: "The Estée Lauder Companies Inc." },
  { favorited: false, symbol: "WELL", name: " Welltower Inc." },
  { favorited: false, symbol: "TRV", name: " The Travelers Companies, Inc." },
  { favorited: false, symbol: "CARR", name: " Carrier Global Corporation" },
  { favorited: false, symbol: "FTNT", name: "Fortinet, Inc." },
  { favorited: false, symbol: "GM", name: " General Motors Company" },
  { favorited: false, symbol: "TFC", name: "Truist Financial Corporation" },
  { favorited: false, symbol: "GWW", name: "W.W. Grainger, Inc." },
  { favorited: false, symbol: "ROST", name: " Ross Stores, Inc." },
  { favorited: false, symbol: "STZ", name: " Constellation Brands, Inc." },
  { favorited: false, symbol: "F", name: " Ford Motor Company" },
  { favorited: false, symbol: "AFL", name: "Aflac Incorporated" },
  { favorited: false, symbol: "LULU", name: "Lululemon Athletica Inc." },
  { favorited: false, symbol: "PSA", name: " Public Storage" },
  { favorited: false, symbol: "URI", name: "United Rentals, Inc." },
  { favorited: false, symbol: "MCHP", name: " Microchip Technology Incorporated" },
  { favorited: false, symbol: "NUE", name: "Nucor Corporation" },
  { favorited: false, symbol: "ODFL", name: "Old Dominion Freight Line, Inc." },
  { favorited: false, symbol: "LEN", name: " Lennar Corporation" },
  { favorited: false, symbol: "WMB", name: "The Williams Companies, Inc." },
  { favorited: false, symbol: "HES", name: " Hess Corporation" },
  { favorited: false, symbol: "IQV", name: "IQVIA Holdings Inc." },
  { favorited: false, symbol: "CCI", name: " Crown Castle Inc." },
  { favorited: false, symbol: "OKE", name: " ONEOK, Inc." },
  { favorited: false, symbol: "O", name: " Realty Income Corporation" },
  { favorited: false, symbol: "TEL", name: "TE Connectivity Ltd." },
  { favorited: false, symbol: "ALL", name: " The Allstate Corporation" },
  { favorited: false, symbol: "AEP", name: "American Electric Power Company, Inc." },
  { favorited: false, symbol: "SRE", name: " Sempra" },
  { favorited: false, symbol: "DLR", name: "Digital Realty Trust, Inc." },
  { favorited: false, symbol: "KHC", name: " The Kraft Heinz Company" },
  { favorited: false, symbol: "FAST", name: "Fastenal Company" },
  { favorited: false, symbol: "MSCI", name: "MSCI Inc." },
  { favorited: false, symbol: "IDXX", name: " IDEXX Laboratories, Inc." },
  { favorited: false, symbol: "JCI", name: " Johnson Controls International plc" },
  { favorited: false, symbol: "AMP", name: "Ameriprise Financial, Inc." },
  { favorited: false, symbol: "PCG", name: " PG&E Corporation" },
  { favorited: false, symbol: "PAYX", name: "Paychex, Inc." },
  { favorited: false, symbol: "BK", name: " The Bank of New York Mellon Corporation" },
  { favorited: false, symbol: "KMB", name: "Kimberly-Clark Corporation" },
  { favorited: false, symbol: "AME", name: "AMETEK, Inc." },
  { favorited: false, symbol: "MRNA", name: " Moderna, Inc." },
  { favorited: false, symbol: "A", name: " Agilent Technologies, Inc." },
  { favorited: false, symbol: "PRU", name: " Prudential Financial, Inc." },
  { favorited: false, symbol: "HUM", name: " Humana Inc." },
  { favorited: false, symbol: "CNC", name: " Centene Corporation" },
  { favorited: false, symbol: "FIS", name: "Fidelity National Information Services, Inc." },
  { favorited: false, symbol: "CHTR", name: " Charter Communications, Inc." },
  { favorited: false, symbol: "KDP", name: " Keurig Dr Pepper Inc." },
  { favorited: false, symbol: "GEHC", name: " GE HealthCare Technologies Inc." },
  { favorited: false, symbol: "KVUE", name: " Kenvue Inc." },
  { favorited: false, symbol: "DOW", name: " Dow Inc." },
  { favorited: false, symbol: "KR", name: " The Kroger Co." },
  { favorited: false, symbol: "NEM", name: " Newmont Corporation" },
  { favorited: false, symbol: "SYY", name: "Sysco Corporation" },
  { favorited: false, symbol: "OTIS", name: "Otis Worldwide Corporation" },
  { favorited: false, symbol: "LHX", name: "L3Harris Technologies, Inc." },
  { favorited: false, symbol: "CMI", name: " Cummins Inc." },
  { favorited: false, symbol: "KMI", name: " Kinder Morgan, Inc." },
  { favorited: false, symbol: "D", name: " Dominion Energy, Inc." },
  { favorited: false, symbol: "CTVA", name: " Corteva, Inc." },
  { favorited: false, symbol: "GIS", name: " General Mills, Inc." },
  { favorited: false, symbol: "HSY", name: " The Hershey Company" },
  { favorited: false, symbol: "CSGP", name: "CoStar Group, Inc." },
  { favorited: false, symbol: "COR", name: " Cencora" },
  { favorited: false, symbol: "YUM", name: "Yum! Brands, Inc." },
  { favorited: false, symbol: "LVS", name: " Las Vegas Sands Corp." },
  { favorited: false, symbol: "IR", name: " Ingersoll Rand Inc." },
  { favorited: false, symbol: "MLM", name: " Martin Marietta Materials, Inc." },
  { favorited: false, symbol: "PWR", name: " Quanta Services, Inc." },
  { favorited: false, symbol: "IT", name: " Gartner, Inc." },
  { favorited: false, symbol: "EXC", name: " Exelon Corporation" },
  { favorited: false, symbol: "CTSH", name: "Cognizant Technology Solutions Corporation" },
  { favorited: false, symbol: "NDAQ", name: "Nasdaq, Inc." },
  { favorited: false, symbol: "VMC", name: " Vulcan Materials Company" },
  { favorited: false, symbol: "RCL", name: "Royal Caribbean Cruises Ltd." },
  { favorited: false, symbol: "EA", name: " Electronic Arts Inc." },
  { favorited: false, symbol: "FANG", name: " Diamondback Energy, Inc." },
  { favorited: false, symbol: "ACGL", name: " Arch Capital Group Ltd." },
  { favorited: false, symbol: "CDW", name: " CDW Corporation" },
  { favorited: false, symbol: "HAL", name: "Halliburton Company" },
  { favorited: false, symbol: "PPG", name: "PPG Industries, Inc." },
  { favorited: false, symbol: "GPN", name: " Global Payments Inc." },
  { favorited: false, symbol: "VRSK", name: " Verisk Analytics, Inc." },
  { favorited: false, symbol: "DG", name: " Dollar General Corporation" },
  { favorited: false, symbol: "BKR", name: "Baker Hughes Company" },
  { favorited: false, symbol: "LYB", name: "LyondellBasell Industries N.V." },
  { favorited: false, symbol: "PEG", name: " Public Service Enterprise Group Incorporated" },
  { favorited: false, symbol: "ROK", name: "Rockwell Automation, Inc." },
  { favorited: false, symbol: "MPWR", name: " Monolithic Power Systems, Inc." },
  { favorited: false, symbol: "EFX", name: " Equifax Inc." },
  { favorited: false, symbol: "ON", name: " ON Semiconductor Corporation" },
  { favorited: false, symbol: "EXR", name: "Extra Space Storage Inc." },
  { favorited: false, symbol: "DD", name: " DuPont de Nemours, Inc." },
  { favorited: false, symbol: "ADM", name: "Archer-Daniels-Midland Company" },
  { favorited: false, symbol: "BIIB", name: "Biogen Inc." },
  { favorited: false, symbol: "DFS", name: " Discover Financial Services" },
  { favorited: false, symbol: "FICO", name: "Fair Isaac Corporation" },
  { favorited: false, symbol: "XYL", name: "Xylem Inc." },
  { favorited: false, symbol: "DVN", name: " Devon Energy Corporation" },
  { favorited: false, symbol: "VICI", name: "VICI Properties Inc." },
  { favorited: false, symbol: "ANSS", name: " ANSYS, Inc." },
  { favorited: false, symbol: "FTV", name: " Fortive Corporation" },
  { favorited: false, symbol: "ED", name: "Consolidated Edison, Inc." },
  { favorited: false, symbol: "HIG", name: " The Hartford Financial Services Group, Inc." },
  { favorited: false, symbol: "CBRE", name: " CBRE Group, Inc." },
  { favorited: false, symbol: "DAL", name: " Delta Air Lines, Inc." },
  { favorited: false, symbol: "HPQ", name: " HP Inc." },
  { favorited: false, symbol: "XEL", name: " Xcel Energy Inc." },
  { favorited: false, symbol: "RMD", name: " ResMed Inc." },
  { favorited: false, symbol: "MTD", name: "Mettler-Toledo International Inc." },
  { favorited: false, symbol: "WST", name: " West Pharmaceutical Services, Inc." },
  { favorited: false, symbol: "GRMN", name: " Garmin Ltd." },
  { favorited: false, symbol: "GLW", name: " Corning Incorporated" },
  { favorited: false, symbol: "WTW", name: "Willis Towers Watson PLC" },
  { favorited: false, symbol: "TSCO", name: "Tractor Supply Company" },
  { favorited: false, symbol: "DLTR", name: "Dollar Tree, Inc." },
  { favorited: false, symbol: "HWM", name: " Howmet Aerospace Inc." },
  { favorited: false, symbol: "CAH", name: " Cardinal Health, Inc." },
  { favorited: false, symbol: "ZBH", name: " Zimmer Biomet Holdings, Inc." },
  { favorited: false, symbol: "KEYS", name: " Keysight Technologies, Inc." },
  { favorited: false, symbol: "EIX", name: " Edison International" },
  { favorited: false, symbol: "RJF", name: "Raymond James Financial, Inc." },
  { favorited: false, symbol: "EBAY", name: " eBay Inc." },
  { favorited: false, symbol: "TROW", name: " T. Rowe Price Group, Inc." },
  { favorited: false, symbol: "WY", name: " Weyerhaeuser Company" },
  { favorited: false, symbol: "AVB", name: "AvalonBay Communities, Inc." },
  { favorited: false, symbol: "WEC", name: " WEC Energy Group, Inc." },
  { favorited: false, symbol: "WAB", name: " Westinghouse Air Brake Technologies Corporation" },
  { favorited: false, symbol: "BLDR", name: "Builders FirstSource, Inc." },
  { favorited: false, symbol: "NVR", name: " NVR, Inc." },
  { favorited: false, symbol: "FITB", name: " Fifth Third Bancorp" },
  { favorited: false, symbol: "TTWO", name: "Take-Two Interactive Software, Inc." },
  { favorited: false, symbol: "CHD", name: " Church & Dwight Co., Inc." },
  { favorited: false, symbol: "ULTA", name: " Ulta Beauty, Inc." },
  { favorited: false, symbol: "BRO", name: " Brown & Brown, Inc." },
  { favorited: false, symbol: "PHM", name: " PulteGroup, Inc." },
  { favorited: false, symbol: "TRGP", name: " Targa Resources Corp." },
  { favorited: false, symbol: "BF.B", name: "Brown-Forman Corporation" },
  { favorited: false, symbol: "MOH", name: "Molina Healthcare, Inc." },
  { favorited: false, symbol: "DOV", name: " Dover Corporation" },
  { favorited: false, symbol: "LYV", name: "Live Nation Entertainment, Inc." },
  { favorited: false, symbol: "DECK", name: " Deckers Outdoor Corporation" },
  { favorited: false, symbol: "ALGN", name: "Align Technology, Inc." },
  { favorited: false, symbol: "BR", name: " Broadridge Financial Solutions, Inc." },
  { favorited: false, symbol: "AXON", name: " Axon Enterprise, Inc." },
  { favorited: false, symbol: "MTB", name: " M&T Bank Corporation" },
  { favorited: false, symbol: "IRM", name: "Iron Mountain Incorporated" },
  { favorited: false, symbol: "EQR", name: "Equity Residential" },
  { favorited: false, symbol: "SBAC", name: "SBA Communications Corporation" },
  { favorited: false, symbol: "STT", name: "State Street Corporation" },
  { favorited: false, symbol: "AWK", name: "American Water Works Company, Inc." },
  { favorited: false, symbol: "STLD", name: " Steel Dynamics, Inc." },
  { favorited: false, symbol: "HPE", name: " Hewlett Packard Enterprise Company" },
  { favorited: false, symbol: "PTC", name: "PTC Inc." },
  { favorited: false, symbol: "ROL", name: " Rollins, Inc." },
  { favorited: false, symbol: "WRB", name: " W. R. Berkley Corporation" },
  { favorited: false, symbol: "STE", name: "STERIS plc" },
  { favorited: false, symbol: "CCL", name: "Carnival Corporation & plc" },
  { favorited: false, symbol: "WDC", name: "Western Digital Corporation" },
  { favorited: false, symbol: "DTE", name: "DTE Energy Company" },
  { favorited: false, symbol: "HUBB", name: "Hubbell Incorporated" },
  { favorited: false, symbol: "ARE", name: "Alexandria Real Estate Equities, Inc." },
  { favorited: false, symbol: "IFF", name: " International Flavors & Fragrances Inc." },
  { favorited: false, symbol: "ETR", name: " Entergy Corporation" },
  { favorited: false, symbol: "CPAY", name: "Corpay, Inc." },
  { favorited: false, symbol: "NTAP", name: " NetApp, Inc." },
  { favorited: false, symbol: "FE", name: " FirstEnergy Corp." },
  { favorited: false, symbol: "APTV", name: " Aptiv PLC" },
  { favorited: false, symbol: "INVH", name: "Invitation Homes Inc." },
  { favorited: false, symbol: "GPC", name: " Genuine Parts Company" },
  { favorited: false, symbol: "ILMN", name: "Illumina, Inc." },
  { favorited: false, symbol: "BAX", name: " Baxter International Inc." },
  { favorited: false, symbol: "BALL", name: " Ball Corporation" },
  { favorited: false, symbol: "TSN", name: "Tyson Foods, Inc." },
  { favorited: false, symbol: "ES", name: " Eversource Energy" },
  { favorited: false, symbol: "CTRA", name: "Coterra Energy Inc." },
  { favorited: false, symbol: "WBD", name: " Warner Bros. Discovery, Inc." },
  { favorited: false, symbol: "WAT", name: " Waters Corporation" },
  { favorited: false, symbol: "MKC", name: "McCormick & Company, Incorporated" },
  { favorited: false, symbol: "TDY", name: "Teledyne Technologies Incorporated" },
  { favorited: false, symbol: "PPL", name: "PPL Corporation" },
  { favorited: false, symbol: "COO", name: "The Cooper Companies, Inc." },
  { favorited: false, symbol: "JBHT", name: " J.B. Hunt Transport Services, Inc." },
  { favorited: false, symbol: "DRI", name: " Darden Restaurants, Inc." },
  { favorited: false, symbol: "PFG", name: " Principal Financial Group, Inc." },
  { favorited: false, symbol: "STX", name: " Seagate Technology Holdings plc" },
  { favorited: false, symbol: "HBAN", name: "Huntington Bancshares Incorporated" },
  { favorited: false, symbol: "K", name: "Kellanova Co" },
  { favorited: false, symbol: "HRL", name: "Hormel Foods Corporation" },
  { favorited: false, symbol: "J", name: "Jacobs Engineering Group Inc." },
  { favorited: false, symbol: "CBOE", name: " Cboe Global Markets, Inc." },
  { favorited: false, symbol: "CINF", name: " Cincinnati Financial Corporation" },
  { favorited: false, symbol: "VLTO", name: "Veralto Corporation" },
  { favorited: false, symbol: "AEE", name: "Ameren Corporation" },
  { favorited: false, symbol: "VRSN", name: "VeriSign, Inc." },
  { favorited: false, symbol: "EXPE", name: " Expedia Group, Inc." },
  { favorited: false, symbol: "CLX", name: " The Clorox Company" },
  { favorited: false, symbol: "TXT", name: "Textron Inc." },
  { favorited: false, symbol: "CE", name: " Celanese Corporation" },
  { favorited: false, symbol: "OMC", name: "Omnicom Group Inc." },
  { favorited: false, symbol: "IEX", name: " IDEX Corporation" },
  { favorited: false, symbol: "RF", name: "Regions Financial Corporation" },
  { favorited: false, symbol: "LH", name: "Laboratory Corporation of America Holdings" },
  { favorited: false, symbol: "WBA", name: "Walgreens Boots Alliance, Inc." },
  { favorited: false, symbol: "CNP", name: " CenterPoint Energy, Inc." },
  { favorited: false, symbol: "HOLX", name: " Hologic, Inc." },
  { favorited: false, symbol: "TYL", name: " Tyler Technologies, Inc." },
  { favorited: false, symbol: "NTRS", name: " Northern Trust Corporation" },
  { favorited: false, symbol: "AVY", name: "Avery Dennison Corporation" },
  { favorited: false, symbol: "VTR", name: "Ventas, Inc." },
  { favorited: false, symbol: "LDOS", name: " Leidos Holdings, Inc." },
  { favorited: false, symbol: "LUV", name: " Southwest Airlines Co." },
  { favorited: false, symbol: "FSLR", name: " First Solar, Inc." },
  { favorited: false, symbol: "CMS", name: " CMS Energy Corporation" },
  { favorited: false, symbol: "ATO", name: "Atmos Energy Corporation" },
  { favorited: false, symbol: "SWKS", name: "Skyworks Solutions, Inc." },
  { favorited: false, symbol: "EXPD", name: " Expeditors International of Washington, Inc." },
  { favorited: false, symbol: "BBY", name: " Best Buy Co., Inc." },
  { favorited: false, symbol: "MAS", name: " Masco Corporation" },
  { favorited: false, symbol: "L", name: "Loews Corporation" },
  { favorited: false, symbol: "SYF", name: "Synchrony Financial" },
  { favorited: false, symbol: "JBL", name: "Jabil Inc." },
  { favorited: false, symbol: "FDS", name: " FactSet Research Systems Inc." },
  { favorited: false, symbol: "EG", name: " Everest Group, Ltd." },
  { favorited: false, symbol: "PKG", name: " Packaging Corporation of America" },
  { favorited: false, symbol: "DPZ", name: "Domino's Pizza, Inc." },
  { favorited: false, symbol: "TER", name: "Teradyne, Inc." },
  { favorited: false, symbol: "AKAM", name: "Akamai Technologies, Inc." },
  { favorited: false, symbol: "CFG", name: "Citizens Financial Group, Inc." },
  { favorited: false, symbol: "ESS", name: "Essex Property Trust, Inc." },
  { favorited: false, symbol: "POOL", name: "Pool Corporation" },
  { favorited: false, symbol: "SNA", name: "Snap-on Incorporated" },
  { favorited: false, symbol: "MAA", name: "Mid-America Apartment Communities, Inc." },
  { favorited: false, symbol: "MRO", name: "Marathon Oil Corporation" },
  { favorited: false, symbol: "TRMB", name: "Trimble Inc." },
  { favorited: false, symbol: "EPAM", name: "EPAM Systems, Inc." },
  { favorited: false, symbol: "CF", name: "CF Industries Holdings, Inc." },
  { favorited: false, symbol: "EQT", name: "EQT Corporation" },
  { favorited: false, symbol: "ZBRA", name: "Zebra Technologies Corporation" },
  { favorited: false, symbol: "LW", name: "Lamb Weston Holdings, Inc." },
  { favorited: false, symbol: "NDSN", name: "Nordson Corporation" },
  { favorited: false, symbol: "NWS", name: "News Corporation" },
  { favorited: false, symbol: "NWSA", name: "News Corporation" },
  { favorited: false, symbol: "UAL", name: "United Airlines Holdings, Inc." },
  { favorited: false, symbol: "ENPH", name: "Enphase Energy, Inc." },
  { favorited: false, symbol: "MGM", name: "MGM Resorts International" },
  { favorited: false, symbol: "DGX", name: "Quest Diagnostics Incorporated" },
  { favorited: false, symbol: "BG", name: "Bunge Limited" },
  { favorited: false, symbol: "HST", name: "Host Hotels & Resorts, Inc." },
  { favorited: false, symbol: "BEN", name: "Franklin Resources, Inc." },
  { favorited: false, symbol: "SWK", name: "Stanley Black & Decker, Inc." },
  { favorited: false, symbol: "NRG", name: "NRG Energy, Inc." },
  { favorited: false, symbol: "TAP", name: "Molson Coors Beverage Company" },
  { favorited: false, symbol: "KEY", name: "KeyCorp" },
  { favorited: false, symbol: "ALB", name: "Albemarle Corporation" },
  { favorited: false, symbol: "GEN", name: "Gen Digital Inc." },
  { favorited: false, symbol: "VTRS", name: "Viatris Inc." },
  { favorited: false, symbol: "FOX", name: "Fox Corporation" },
  { favorited: false, symbol: "FOXA", name: "Fox Corporation" },
  { favorited: false, symbol: "LKQ", name: "LKQ Corporation" },
  { favorited: false, symbol: "CAG", name: "Conagra Brands, Inc." },
  { favorited: false, symbol: "PNR", name: "Pentair plc" },
  { favorited: false, symbol: "IP", name: "International Paper Company" },
  { favorited: false, symbol: "CRL", name: "Charles River Laboratories International, Inc." },
  { favorited: false, symbol: "KMX", name: "CarMax, Inc." },
  { favorited: false, symbol: "AMCR", name: "Amcor plc" },
  { favorited: false, symbol: "SJM", name: "The J. M. Smucker Company" },
  { favorited: false, symbol: "CPB", name: "Campbell Soup Company" },
  { favorited: false, symbol: "AOS", name: "A. O. Smith Corporation" },
  { favorited: false, symbol: "RVTY", name: "Revvity, Inc." },
  { favorited: false, symbol: "UDR", name: "UDR, Inc." },
  { favorited: false, symbol: "INCY", name: "Incyte Corporation" },
  { favorited: false, symbol: "KIM", name: "Kimco Realty Corporation" },
  { favorited: false, symbol: "WRK", name: "WestRock Company" },
  { favorited: false, symbol: "DOC", name: "Healthpeak Properties, Inc." },
  { favorited: false, symbol: "IPG", name: "The Interpublic Group of Companies, Inc." },
  { favorited: false, symbol: "LNT", name: "Alliant Energy Corporation" },
  { favorited: false, symbol: "JKHY", name: "Jack Henry & Associates, Inc." },
  { favorited: false, symbol: "UHS", name: "Universal Health Services, Inc." },
  { favorited: false, symbol: "NI", name: "NiSource Inc." },
  { favorited: false, symbol: "JNPR", name: "Juniper Networks, Inc." },
  { favorited: false, symbol: "PODD", name: "Insulet Corporation" },
  { favorited: false, symbol: "AES", name: "The AES Corporation" },
  { favorited: false, symbol: "DVA", name: "DaVita Inc." },
  { favorited: false, symbol: "EVRG", name: "Evergy, Inc." },
  { favorited: false, symbol: "ALLE", name: "Allegion plc" },
  { favorited: false, symbol: "EMN", name: "Eastman Chemical Company" },
  { favorited: false, symbol: "RL", name: "Ralph Lauren Corporation" },
  { favorited: false, symbol: "HII", name: "Huntington Ingalls Industries, Inc." },
  { favorited: false, symbol: "WYNN", name: "Wynn Resorts, Limited" },
  { favorited: false, symbol: "REG", name: "Regency Centers Corporation" },
  { favorited: false, symbol: "FFIV", name: "F5, Inc." },
  { favorited: false, symbol: "QRVO", name: "Qorvo, Inc." },
  { favorited: false, symbol: "GL", name: "Globe Life Inc." },
  { favorited: false, symbol: "BBWI", name: "Bath & Body Works, Inc." },
  { favorited: false, symbol: "PAYC", name: "Paycom Software, Inc." },
  { favorited: false, symbol: "TECH", name: "Bio-Techne Corporation" },
  { favorited: false, symbol: "TPR", name: "Tapestry, Inc." },
  { favorited: false, symbol: "TFX", name: "Teleflex Incorporated" },
  { favorited: false, symbol: "CPT", name: "Camden Property Trust" },
  { favorited: false, symbol: "DAY", name: "Dayforce Inc" },
  { favorited: false, symbol: "CTLT", name: "Catalent, Inc." },
  { favorited: false, symbol: "AAL", name: "American Airlines Group Inc." },
  { favorited: false, symbol: "APA", name: "APA Corporation" },
  { favorited: false, symbol: "MOS", name: "The Mosaic Company" },
  { favorited: false, symbol: "BXP", name: "Boston Properties, Inc." },
  { favorited: false, symbol: "AIZ", name: "Assurant, Inc." },
  { favorited: false, symbol: "BIO", name: "Bio-Rad Laboratories, Inc." },
  { favorited: false, symbol: "MTCH", name: "Match Group, Inc." },
  { favorited: false, symbol: "HSIC", name: "Henry Schein, Inc." },
  { favorited: false, symbol: "CZR", name: "Caesars Entertainment, Inc." },
  { favorited: false, symbol: "NCLH", name: "Norwegian Cruise Line Holdings Ltd." },
  { favorited: false, symbol: "CHRW", name: "C.H. Robinson Worldwide, Inc." },
  { favorited: false, symbol: "FRT", name: "Federal Realty Investment Trust" },
  { favorited: false, symbol: "RHI", name: "Robert Half International Inc." },
  { favorited: false, symbol: "PNW", name: "Pinnacle West Capital Corporation" },
  { favorited: false, symbol: "MKTX", name: "MarketAxess Holdings Inc." },
  { favorited: false, symbol: "ETSY", name: "Etsy, Inc." },
  { favorited: false, symbol: "MHK", name: "Mohawk Industries, Inc." },
  { favorited: false, symbol: "BWA", name: "BorgWarner Inc." },
  { favorited: false, symbol: "FMC", name: "FMC Corporation" },
  { favorited: false, symbol: "PARA", name: "Paramount Global" },
  { favorited: false, symbol: "HAS", name: "Hasbro, Inc." },
  { favorited: false, symbol: "IVZ", name: "Invesco Ltd." },
  { favorited: false, symbol: "CMA", name: "Comerica Incorporated" },
  { favorited: false, symbol: "GNRC", name: "Generac Holdings Inc." },
  { favorited: false, symbol: "XRAY", name: "DENTSPLY SIRONA Inc." },
  { favorited: false, symbol: "VFC", name: "V.F. Corporation" },
];
